/* generated by dia/codegen.py */
/*(NULL)*/
class Wektor2D 
{
public:
	Wektory2D operator + (const Wektor2D& W);
	double[2] _Wsp;
};

/*(NULL)*/
class Scena 
{
public:
	void PrzesunProstokaty (const Wektor2D& Trans);
	Prostokat[3] ZbProstokatow;
};

/*(NULL)*/
class Prostokąt 
{
public:
	void Przesun (const Wektor2D& Trans);
	Wektor2D[4] Wierzcholki;
};

